Bump k8s api to v0.29.2
devfile/api pull request #1545
Opened 2024-05-13 04:55 UTC by Kartikey-star

These changes are required so as to fix  an incompatibility with the k8s api in devfile/library which was witnessed as part of https://github.com/openshift/console/pull/13816.

2024-05-13 15:49 UTC, michael-valdron commented
Hi @Kartikey-star, thanks for your PR contribution! The devfile services team will be create a series of issues to address your changes and what is being blocked from incompatibility with Kubernetes 1.29.

If you don't mind, we would like to use your PR branch to assess the next devfile api version target for these changes.

cc @devfile/devfile-services-team

2024-05-15 15:30 UTC, michael-valdron commented
fixes #1556

2024-05-16 14:04 UTC, michael-valdron requested changes
@Kartikey-star Need to commit changes from running `go mod tidy && go mod vendor` locally.

2024-05-21 22:58 UTC, michael-valdron reviewed
Changes looks good to me, should receive a review from one of the code owners.

cc @yangcao77 @johnmcollier

2024-05-22 16:58 UTC, yangcao77 approved these changes
lgtm

2024-05-22 18:18 UTC, johnmcollier approved these changes

2024-05-27 08:57 UTC, thepetk approved these changes
/lgtm

2024-05-27 08:57 UTC, merged