Update meetings information under GOVERNANCE
devfile/api pull request #1596
Opened 2024-06-11 19:39 UTC by michael-valdron

## What does this PR do?

Updates the out of date information about meetings under `GOVERNANCE.md` to point to the Meetings section of our community page. Meetings are now ad-hoc instead of every Monday at 9AM EST on a regular schedule.

### Which issue(s) does this PR fix

https://github.com/devfile/api/issues/1515

### PR acceptance criteria

Testing and documentation do not need to be complete in order for this PR to be approved. We just need to ensure tracking issues are opened.

> - Open new test/doc issues under the [devfile/api](https://github.com/devfile/api/issues) repo
> - Check each criteria if:
> - There is a separate tracking issue. Add the issue link under the criteria
>  **or**
> - test/doc updates are made as part of this PR
> - If unchecked, explain why it's not needed

- [ ] Unit/Functional tests

  

- [ ] [QE Integration test](https://github.com/devfile/integration-tests)

  

- [ ] Documentation

   

- [ ] Client Impact

  

### How to test changes / Special notes to the reviewer

2024-06-11 19:47 UTC, Jdubrick requested changes

2024-06-11 19:47 UTC, Jdubrick commented on GOVERNANCE.md
> +developer meetings, for more information about these meetings see the [Meetings section of Devfile community page](https://devfile.io/docs/2.3.0/community#meetings).
```suggestion
developer meetings. For more information about these meetings see the [Meetings section of the Devfile community page](https://devfile.io/docs/2.3.0/community#meetings).
```

nit

2024-06-11 19:54 UTC, michael-valdron commented
> Client Impact

N/A

2024-06-11 19:59 UTC, Jdubrick approved these changes
/lgtm

2024-06-12 08:16 UTC, thepetk approved these changes
/lgtm

2024-06-12 16:14 UTC, michael-valdron commented
@johnmcollier @yangcao77 Could one of you sign off as well if everything looks good.

2024-06-12 16:38 UTC, johnmcollier approved these changes

2024-06-12 16:48 UTC, merged