Add security.md
devfile/api pull request #1627
Opened 2024-08-22 10:56 UTC by thepetk

# Description of Changes

This PR adds a security policy with vulnerability reporting instructions.

# Related Issue(s)
Fixes https://github.com/devfile/api/issues/1461

# Acceptance Criteria

_Testing and documentation do not need to be complete in order for this PR to be approved. However, tracking issues must be opened for missing testing/documentation._

New testing and documentation issues can be opened under [`devfile/api/issues`](https://github.com/devfile/api/issues).

You can check the respective criteria below if either of the following is true:
- There is a separate tracking issue opened and that issue is linked in this PR.
- Testing/documentation updates are contained within this PR.

If criteria is left unchecked please provide an explanation why.

- [ ] Unit/Functional tests

  

- [ ] [QE Integration test](https://github.com/devfile/integration-tests)

  

- [ ] Documentation

   

- [ ] Client Impact

  

# Tests Performed
_Explain what tests you personally ran to ensure the changes are functioning as expected._

# How To Test
_Instructions for the reviewer on how to test your changes._

# Notes To Reviewer
_Any notes you would like to include for the reviewer._

2024-08-22 13:27 UTC, yangcao77 approved these changes

2024-08-22 23:16 UTC, michael-valdron requested changes

2024-08-22 23:16 UTC, michael-valdron commented on SECURITY.md
> +An email to <a href="mailto:team-devfile@redhat.com">team-devfile@redhat.com</a> is the preferred mechanism for outside users to report security issues. A member of the devfile team will open the req
We'll need a different contact email as this one can not receive external emails.

FYI @devfile/devfile-services-team

2024-09-03 15:58 UTC, Jdubrick approved these changes
Minor nits, you don't need to incorporate these changes however lgtm

2024-09-03 15:58 UTC, Jdubrick commented on SECURITY.md
> +## Reporting process
```suggestion
## Reporting Process
```

2024-09-03 15:58 UTC, Jdubrick commented on SECURITY.md
> +### Email team devfile
```suggestion
## Contact Us
```

2024-09-03 15:58 UTC, Jdubrick commented on SECURITY.md
> +### What to avoid
```suggestion
## What To Avoid
```

2024-09-03 16:03 UTC, michael-valdron reviewed
Just a suggested change to the Reporting process section, other than that changes lgtm.

2024-09-03 16:03 UTC, michael-valdron commented on SECURITY.md
> +When a security vulnerability is found is important to not accidentally broadcast to the world that the issue exists, as this makes it easier for people to exploit it. The preferred way of reporting
```suggestion
When a security vulnerability is found, it is important to not accidentally broadcast publicly that the issue exists to avoid potential exploits. The preferred way of reporting security issues in Devfiles is listed below.
```

2024-09-03 16:05 UTC, thepetk commented
> Just a suggested change to the Reporting process section, other than that changes lgtm.

@michael-valdron I've updated the content

2024-09-03 16:05 UTC, michael-valdron approved these changes
/lgtm

2024-09-03 16:12 UTC, merged