Initial proposal for Console devfile feature w/o Build Guidance Spec
devfile/api pull request #219
Opened 2020-11-17 19:56 UTC by maysunfaisal

Signed-off-by: Maysun J Faisal <maysunaneek@gmail.com>

### What does this PR do?
This PR outlines a proposal for the OpenShift Console to consume build guidance within the boundaries of devfile spec 2.0.0 because the Build Guidance spec PR #127 is still an open discussion.

### What issues does this PR fix or reference?
This proposal is for the POC PR https://github.com/openshift/console/pull/6321

### Is your PR tested? Consider putting some instruction how to test your changes

#### Docs PR

2020-11-19 22:27 UTC, elsony requested changes

2020-11-19 22:27 UTC, elsony commented on docs/proposals/console/devfile-import.md
> +If we want to decouple `ImageStream` and `ImageStreamTag` from the application name, so that a custom image name can be specified in the devfile's component container; then we would need to update 1.
Format the 3 points.

2020-11-19 22:27 UTC, elsony commented on docs/proposals/console/devfile-import.md
> +<img src="https://user-images.githubusercontent.com/31771087/99319306-4c19be80-2837-11eb-9639-a5c130deb4ba.png">
We should clarify that the first phase of the implementation will only support DockerFile, SourceToImage will not be implemented.

2020-11-19 22:27 UTC, elsony commented on docs/proposals/console/devfile-import.md
> +The above devfile proposal and POC PR assumes the `BuildConfig` outputs the build to an `ImageStreamTag` which is used by the OpenShift internal registry. To push the image to a non-OpenShift Image R
To scope the work on the first phase, we should probably clarify that we are going to implement the ImageStream path only. We are not going to implement the private or dockerhub registry on the first phase of the implementation.

2020-11-20 17:10 UTC, maysunfaisal commented on docs/proposals/console/devfile-import.md
> +If we want to decouple `ImageStream` and `ImageStreamTag` from the application name, so that a custom image name can be specified in the devfile's component container; then we would need to update 1.
Updated

2020-11-20 17:10 UTC, maysunfaisal commented on docs/proposals/console/devfile-import.md
> +<img src="https://user-images.githubusercontent.com/31771087/99319306-4c19be80-2837-11eb-9639-a5c130deb4ba.png">
Updated

2020-11-20 17:10 UTC, maysunfaisal commented on docs/proposals/console/devfile-import.md
> +The above devfile proposal and POC PR assumes the `BuildConfig` outputs the build to an `ImageStreamTag` which is used by the OpenShift internal registry. To push the image to a non-OpenShift Image R
Updated

2020-11-20 17:35 UTC, johnmcollier requested changes

2020-11-20 17:35 UTC, johnmcollier commented on docs/proposals/console/devfile-import.md
> +Here is a proposed 2.0.0 spec devfile that can support build guidance for OpenShift Console:
Can you make it clear what exactly your proposal will add/change? It's a little hard to tell what's changing, apart from the `alpha.build-dockerfile` attribute.

2020-11-20 17:40 UTC, maysunfaisal commented on docs/proposals/console/devfile-import.md
> +Here is a proposed 2.0.0 spec devfile that can support build guidance for OpenShift Console:
That is perhaps the only change without the build guidance spec in the current devfile spec. I'll be more clear!

2020-11-20 17:43 UTC, johnmcollier commented on docs/proposals/console/devfile-import.md
> +Here is a proposed 2.0.0 spec devfile that can support build guidance for OpenShift Console:
Okay, that makes sense.

2020-11-20 17:49 UTC, maysunfaisal commented on docs/proposals/console/devfile-import.md
> +Here is a proposed 2.0.0 spec devfile that can support build guidance for OpenShift Console:
Updated

2020-12-16 19:16 UTC, elsony approved these changes
/lgtm

2020-12-16 19:55 UTC, johnmcollier approved these changes

2020-12-16 19:57 UTC, merged