Fix default value of buildContext to PROJECTS_ROOT
devfile/api pull request #692
Opened 2021-11-24 09:29 UTC by feloy

### What does this PR do?:

The PR fixes a comment indicating a wrong environment variable name.

### Which issue(s) this PR fixes:

### PR acceptance criteria:
Testing and documentation do not need to be complete in order for this PR to be approved. We just need to ensure tracking issues are opened.

> - Open new test/doc issues under the [devfile/api](https://github.com/devfile/api/issues) repo
> - Check each criteria if:
>  - There is a separate tracking issue. Add the issue link under the criteria
>  **or**
>  - test/doc updates are made as part of this PR
> -  If unchecked, explain why it's not needed

- [ ] Unit/Functional tests

  

- [ ] [QE Integration test](https://github.com/devfile/integration-tests) 

  

- [ ] Documentation 

   

- [ ] Client Impact

  

### How to test changes / Special notes to the reviewer:

2021-11-24 14:32 UTC, amisevsk approved these changes

2021-11-24 20:18 UTC, maysunfaisal approved these changes

2021-11-24 20:20 UTC, maysunfaisal commented on pkg/apis/workspaces/v1alpha2/component_image_dockerfile.go
> +	// Path of source directory to establish build context. Defaults to ${PROJECTS_ROOT} in the container
pls run `build.sh` to regen the spec description

2021-11-25 16:04 UTC, maysunfaisal approved these changes

2022-02-22 11:55 UTC, kadel commented on pkg/apis/workspaces/v1alpha2/component_image_dockerfile.go
> +	// Path of source directory to establish build context. Defaults to ${PROJECTS_ROOT} in the container
@elsony @l0rd Wouldn't it be better if ti default to `$PROJECT_SOURCE` ?

2022-03-08 11:35 UTC, l0rd requested changes
+1 to @kadel. We should deprecate the use of `$PROJECTS_ROOT`. See https://github.com/devfile/api/issues/681#issuecomment-972827473 and https://github.com/devfile/api/issues/679 ("Deprecate PROJECTS_ROOT and move to use PROJECT_SOURCE")

2022-03-09 17:00 UTC, amisevsk approved these changes

2022-03-11 10:00 UTC, l0rd approved these changes

2022-03-15 15:32 UTC, merged