Restore v1alpha1 DevWorkspace CRD
devfile/api pull request #738
Opened 2022-01-20 17:24 UTC by amisevsk

### What does this PR do?:
This commit effectively reverts https://github.com/devfile/api/pull/639, restoring the `v1alpha1` version of the DevWorkspace to the devfile API. This is required as, after we merged the PR above, we discovered that the OpenShift Console still depends on the v1alpha1 apiVersion.

### Which issue(s) this PR fixes:
Closes https://github.com/devfile/api/issues/721

### PR acceptance criteria:
- [x] Unit/Functional tests

- [ ] [QE Integration test](https://github.com/devfile/integration-tests) 
    - I believe no changes are required here

- [ ] Documentation 
    - Documenation is unchanged

- [ ] Client Impact
    - No breaking changes

### How to test changes / Special notes to the reviewer:
Test that v1alpha1 API is restored to CRDs. The Devfile schema should be unchanged.

2022-01-24 23:15 UTC, yangcao77 commented on crds/workspace.devfile.io_devworkspaces.v1beta1.yaml
> +                                              description: "Descr
those fields added in v1alpha2 should not be included in v1alpha1? similar as other files.

2022-01-25 17:40 UTC, yangcao77 requested changes
Since it's a revert of #639 , I don't see any difference compare with files before changes in #639 . Just need to add one missing vendor.

2022-01-25 17:40 UTC, yangcao77 commented on pkg/apis/workspaces/v1alpha1/devworkspace_conversion.go
> +	"sigs.k8s.io/controller-runtime/pkg/conversion"
this go module is missing in vendor

2022-01-25 18:10 UTC, yangcao77 commented
changes look good. just need to pass the ci, and I will add the label.

2022-01-25 19:57 UTC, amisevsk commented
Running build.sh makes no changes locally, and trying `./docker-run.sh ./build.sh` gives 
```
check ./build.sh
Building image quay.io/devfile/kubernetes-api-build-prerequisites:latest...[OK]
Running ./build.sh
bash: line 1: ./build.sh: Permission denied
Fail to run the script
```
:thinking:

2022-01-25 21:32 UTC, yangcao77 approved these changes

2022-01-26 14:41 UTC, merged