docs: adding contribution guidelines
devfile/api pull request #823
Opened 2022-04-12 19:21 UTC by mike-hoang

Signed-off-by: Michael Hoang <mhoang@redhat.com>

### What does this PR do?:
Adds a contributing file which is a requirement for CNCF onboarding

### Which issue(s) this PR fixes:
https://github.com/devfile/api/issues/772

### PR acceptance criteria:
Testing and documentation do not need to be complete in order for this PR to be approved. We just need to ensure tracking issues are opened.

> - Open new test/doc issues under the [devfile/api](https://github.com/devfile/api/issues) repo
> - Check each criteria if:
>  - There is a separate tracking issue. Add the issue link under the criteria
>  **or**
>  - test/doc updates are made as part of this PR
> -  If unchecked, explain why it's not needed

- [ ] Unit/Functional tests

- [ ] [QE Integration test](https://github.com/devfile/integration-tests) 

- [x] Documentation 

- [ ] Client Impact

### How to test changes / Special notes to the reviewer:

2022-04-12 23:35 UTC, johnmcollier approved these changes

2022-04-13 14:38 UTC, yangcao77 requested changes
Left some comments. 
Can you also add a guide for testing? and also a guide for building?

2022-04-13 14:38 UTC, yangcao77 commented on CONTRIBUTING.md
> +- Issues are tracked via the the [devfile/api](https://github.com/devfile/api) repo. Open or search for issues on the [devfile/api](https://github.com/devfile/api) repo with the label `area/api`.
```suggestion
- Open or search for [issues](https://github.com/devfile/api/issues) with the label `area/api`.
```

2022-04-13 14:38 UTC, yangcao77 commented on CONTRIBUTING.md
> +- Search for existing pull requests or issues that are related before you start a PR.
duplicated with first point

2022-04-13 15:11 UTC, amisevsk reviewed
Generally looks good to me, apart from Stephanie's review.

2022-04-13 15:11 UTC, amisevsk commented on CONTRIBUTING.md
> +After addressing review comments, don’t forget to add a comment in the PR afterward, so everyone gets notified by Github and know to re-review.
```suggestion
After addressing review comments, don’t forget to add a comment in the PR afterward, so everyone gets notified by Github and knows to re-review.
```

2022-04-13 17:15 UTC, mike-hoang commented on CONTRIBUTING.md
> +- Search for existing pull requests or issues that are related before you start a PR.
removed

2022-04-13 17:15 UTC, mike-hoang commented on CONTRIBUTING.md
> +`Signed-off-by: First Lastname <email@email.com>`
removed the inline and switched to block

2022-04-13 18:01 UTC, yangcao77 approved these changes
changes lgtm

2022-04-19 17:58 UTC, amisevsk approved these changes

2022-04-19 17:58 UTC, amisevsk commented on CONTRIBUTING.md
> +```
Worth noting (perhaps) that on some SELinux configurations, this command fails "permission denied". The current workaround I use is to add `:Z` to the volume mount, though this is probably not ideal.

2022-04-22 14:59 UTC, amisevsk commented on CONTRIBUTING.md
> +```
:+1: makes sense to me

2022-04-29 16:24 UTC, merged